version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.20.2-browsers
    steps:
      - checkout
      - run:
          name: Check current version of node
          command: node -v
      - restore_cache:
          keys:
            - node_modules_cache_{{ checksum "package-lock.json" }}
      - run: 
          name: Install QuML Library dependencies
          command: cd projects/quml-library &&  npm install --no-progress
      - run:
          name: Install project dependencies
          command: |
            if [ ! -d "node_modules" ]; then
            npm i -f
            fi
      - save_cache:
          key: node_modules_cache_{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test QuML
          command: npm run test-lib-ci
      - run:
          name: Publish to NPM
          command: |
            if [ -z $CIRCLE_PR_NUMBER ]; then
              npm run build-lib && npm pack ./dist/quml-library
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              npm publish project-sunbird-sunbird-quml-player-v9-*
            else
              npm run build-lib && npm pack ./dist/quml-library
            fi